/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package User_end.User_intro;

/**
 *
 * @author Atharva Sahani
 */
public class User_intro_home extends javax.swing.JFrame {

    /**
     * Creates new form User_intro_home
     */
    public User_intro_home() {
        initComponents();
        setSize(1680,1080);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        j3 = new javax.swing.JLabel();
        j5 = new javax.swing.JLabel();
        j7 = new javax.swing.JLabel();
        j1 = new javax.swing.JLabel();
        j2 = new javax.swing.JLabel();
        j4 = new javax.swing.JLabel();
        j8 = new javax.swing.JLabel();
        j6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        j3.setIcon(new javax.swing.ImageIcon("J:\\resources\\pics1\\Drinks HD Wallpapers (6).jpg")); // NOI18N
        j3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j3MouseClicked(evt);
            }
        });
        getContentPane().add(j3);
        j3.setBounds(970, 40, 370, 184);

        j5.setIcon(new javax.swing.ImageIcon("J:\\resources\\pics1\\wallpaper-pizza-food.jpg")); // NOI18N
        j5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j5MouseClicked(evt);
            }
        });
        getContentPane().add(j5);
        j5.setBounds(140, 380, 400, 184);

        j7.setIcon(new javax.swing.ImageIcon("J:\\resources\\pics1\\1.jpg")); // NOI18N
        j7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j7MouseClicked(evt);
            }
        });
        getContentPane().add(j7);
        j7.setBounds(920, 384, 380, 190);

        j1.setIcon(new javax.swing.ImageIcon("J:\\resources\\pics1\\IMG_139077.jpg")); // NOI18N
        j1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j1MouseClicked(evt);
            }
        });
        getContentPane().add(j1);
        j1.setBounds(130, 60, 400, 184);

        j2.setForeground(new java.awt.Color(240, 240, 240));
        j2.setText("Event Booking");
        j2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j2MouseClicked(evt);
            }
        });
        getContentPane().add(j2);
        j2.setBounds(130, 260, 350, 36);

        j4.setForeground(new java.awt.Color(240, 240, 240));
        j4.setText("Order Food Online");
        j4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j4MouseClicked(evt);
            }
        });
        getContentPane().add(j4);
        j4.setBounds(970, 240, 370, 38);

        j8.setForeground(new java.awt.Color(240, 240, 240));
        j8.setText("Manage user details");
        j8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j8MouseClicked(evt);
            }
        });
        getContentPane().add(j8);
        j8.setBounds(920, 600, 370, 37);

        j6.setForeground(new java.awt.Color(240, 240, 240));
        j6.setText("Reservation");
        j6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j6MouseClicked(evt);
            }
        });
        getContentPane().add(j6);
        j6.setBounds(140, 590, 410, 37);

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\resources\\pics\\5075239-plain-black-wallpaper.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1490, 820);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void j1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j1MouseClicked
        new User_end.Booking_Event.Booking_event_home().setVisible(true);
          this.dispose();
    }//GEN-LAST:event_j1MouseClicked

    private void j2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j2MouseClicked
        new User_end.Booking_Event.Booking_event_home().setVisible(true);
          this.dispose();
    }//GEN-LAST:event_j2MouseClicked

    private void j5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j5MouseClicked
        new User_end.Booking_reservation.Reservation().setVisible(true);
          this.dispose();
    }//GEN-LAST:event_j5MouseClicked

    private void j6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j6MouseClicked
       new User_end.Booking_reservation.Reservation().setVisible(true);
          this.dispose();
    }//GEN-LAST:event_j6MouseClicked

    private void j3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j3MouseClicked
          new User_end.Online_order.Online_order_home_page().setVisible(true);
          this.dispose();
                       
    }//GEN-LAST:event_j3MouseClicked

    private void j4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j4MouseClicked
           new User_end.Online_order.Online_order_home_page().setVisible(true);
          this.dispose();
    
    }//GEN-LAST:event_j4MouseClicked

    private void j7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j7MouseClicked
         new User_end.User_details.Managing_user_details_page_home().setVisible(true);
          this.dispose();
    }//GEN-LAST:event_j7MouseClicked

    private void j8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j8MouseClicked
       new User_end.User_details.Managing_user_details_page_home().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_j8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User_intro_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User_intro_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User_intro_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_intro_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User_intro_home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel j1;
    private javax.swing.JLabel j2;
    private javax.swing.JLabel j3;
    private javax.swing.JLabel j4;
    private javax.swing.JLabel j5;
    private javax.swing.JLabel j6;
    private javax.swing.JLabel j7;
    private javax.swing.JLabel j8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    // End of variables declaration//GEN-END:variables
}
