/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package User_end.Online_order;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author Atharva Sahani
 */
public class Menu_shop_1_view extends javax.swing.JFrame {

    /**
     * Creates new form Menu_shop_2_view
     */
    public Menu_shop_1_view() {
        initComponents();
        try{
           Connection con=null;
           Class.forName("oracle.jdbc.driver.OracleDriver");
           con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521/xe","system","vedaang" );
           PreparedStatement pst=con.prepareStatement("Select * from Desi_outlet" );
           ResultSet x=pst.executeQuery();
           String sno[]=new String[7];
           String name[]=new String[7];
           String description[]=new String[7];
           Integer price[]=new Integer[7];
           int i=0;
           while(x.next())
           {
           sno[i]=x.getString(1);
           name[i]=x.getString(2);
           description[i]=x.getString(3);
           price[i]=Integer.parseInt(x.getString(4));
           i++;
           }
           s1.setText(sno[0]);
           s2.setText(sno[1]);
           s3.setText(sno[2]);
           s4.setText(sno[3]);
           s5.setText(sno[4]);
           s6.setText(sno[5]);
           s7.setText(sno[6]);
           n1.setText(name[0]);
           n2.setText(name[1]);
           n3.setText(name[2]);
           n4.setText(name[3]);
           n5.setText(name[4]);
           n6.setText(name[5]);
           n7.setText(name[6]);
           d1.setText(description[0]);
           d2.setText(description[1]);
           d3.setText(description[2]);
           d4.setText(description[3]);
           d5.setText(description[4]);
           d6.setText(description[5]);
           d7.setText(description[6]);
           p1.setText(Integer.toString(price[0]));
           p2.setText(Integer.toString(price[1]));
           p3.setText(Integer.toString(price[2]));
           p4.setText(Integer.toString(price[3]));
           p5.setText(Integer.toString(price[4]));
           p6.setText(Integer.toString(price[5]));
           p7.setText(Integer.toString(price[6]));
           
           con.close();
        }catch(Exception e)
        { 
            System.out.println(e);
        }
        }
   
     /* This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        s1 = new javax.swing.JLabel();
        n1 = new javax.swing.JLabel();
        d1 = new javax.swing.JLabel();
        p1 = new javax.swing.JLabel();
        d2 = new javax.swing.JLabel();
        p2 = new javax.swing.JLabel();
        s2 = new javax.swing.JLabel();
        n2 = new javax.swing.JLabel();
        d3 = new javax.swing.JLabel();
        n3 = new javax.swing.JLabel();
        p3 = new javax.swing.JLabel();
        s3 = new javax.swing.JLabel();
        d4 = new javax.swing.JLabel();
        p4 = new javax.swing.JLabel();
        n4 = new javax.swing.JLabel();
        s4 = new javax.swing.JLabel();
        s5 = new javax.swing.JLabel();
        n5 = new javax.swing.JLabel();
        d5 = new javax.swing.JLabel();
        p5 = new javax.swing.JLabel();
        p6 = new javax.swing.JLabel();
        n6 = new javax.swing.JLabel();
        d6 = new javax.swing.JLabel();
        s6 = new javax.swing.JLabel();
        n7 = new javax.swing.JLabel();
        s7 = new javax.swing.JLabel();
        d7 = new javax.swing.JLabel();
        p7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("S.no");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 11, 74, 32);

        jLabel2.setText("Name of Dish");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(154, 15, 325, 25);

        jLabel3.setText("Description");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(154, 49, 325, 14);

        jLabel4.setText("Price");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(706, 11, 59, 35);

        s1.setText("S.no");
        getContentPane().add(s1);
        s1.setBounds(10, 95, 74, 32);

        n1.setText("Name of Dish");
        getContentPane().add(n1);
        n1.setBounds(154, 99, 325, 25);

        d1.setText("Description");
        getContentPane().add(d1);
        d1.setBounds(154, 135, 325, 14);

        p1.setText("Price");
        getContentPane().add(p1);
        p1.setBounds(706, 94, 59, 35);

        d2.setText("Description");
        getContentPane().add(d2);
        d2.setBounds(154, 208, 325, 14);

        p2.setText("Price");
        getContentPane().add(p2);
        p2.setBounds(706, 167, 59, 35);

        s2.setText("S.no");
        getContentPane().add(s2);
        s2.setBounds(10, 167, 74, 32);

        n2.setText("Name of Dish");
        getContentPane().add(n2);
        n2.setBounds(154, 177, 325, 25);

        d3.setText("Description");
        getContentPane().add(d3);
        d3.setBounds(154, 281, 325, 14);

        n3.setText("Name of Dish");
        getContentPane().add(n3);
        n3.setBounds(154, 245, 325, 25);

        p3.setText("Price");
        getContentPane().add(p3);
        p3.setBounds(706, 386, 59, 35);

        s3.setText("S.no");
        getContentPane().add(s3);
        s3.setBounds(10, 240, 74, 32);

        d4.setText("Description");
        getContentPane().add(d4);
        d4.setBounds(154, 354, 325, 14);

        p4.setText("Price");
        getContentPane().add(p4);
        p4.setBounds(706, 240, 59, 35);

        n4.setText("Name of Dish");
        getContentPane().add(n4);
        n4.setBounds(154, 318, 325, 25);

        s4.setText("S.no");
        getContentPane().add(s4);
        s4.setBounds(10, 313, 74, 32);

        s5.setText("S.no");
        getContentPane().add(s5);
        s5.setBounds(10, 406, 74, 32);

        n5.setText("Name of Dish");
        getContentPane().add(n5);
        n5.setBounds(154, 396, 325, 25);

        d5.setText("Description");
        getContentPane().add(d5);
        d5.setBounds(154, 427, 325, 14);

        p5.setText("Price");
        getContentPane().add(p5);
        p5.setBounds(706, 313, 59, 35);

        p6.setText("Price");
        getContentPane().add(p6);
        p6.setBounds(706, 462, 59, 35);

        n6.setText("Name of Dish");
        getContentPane().add(n6);
        n6.setBounds(154, 462, 325, 25);

        d6.setText("Description");
        getContentPane().add(d6);
        d6.setBounds(154, 503, 325, 14);

        s6.setText("S.no");
        getContentPane().add(s6);
        s6.setBounds(10, 462, 74, 32);

        n7.setText("Name of Dish");
        getContentPane().add(n7);
        n7.setBounds(154, 552, 325, 25);

        s7.setText("S.no");
        getContentPane().add(s7);
        s7.setBounds(10, 552, 74, 32);

        d7.setText("Description");
        getContentPane().add(d7);
        d7.setBounds(154, 590, 325, 14);

        p7.setText("Price");
        getContentPane().add(p7);
        p7.setBounds(706, 552, 59, 35);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 653, 190, 30);

        jButton2.setText("Yes");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(600, 650, 100, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Wish to order ????????-----");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(340, 650, 250, 30);

        jButton4.setText("No");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(720, 650, 100, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new User_end.Online_order.Online_order_home_page().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       new Menu_shop_1_order().setVisible(true);
       this.dispose();
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new User_end.Online_order.Online_order_home_page().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_shop_1_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_shop_1_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_shop_1_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_shop_1_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_shop_1_view().setVisible(true);
              
                
               
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel d1;
    private javax.swing.JLabel d2;
    private javax.swing.JLabel d3;
    private javax.swing.JLabel d4;
    private javax.swing.JLabel d5;
    private javax.swing.JLabel d6;
    private javax.swing.JLabel d7;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel n1;
    private javax.swing.JLabel n2;
    private javax.swing.JLabel n3;
    private javax.swing.JLabel n4;
    private javax.swing.JLabel n5;
    private javax.swing.JLabel n6;
    private javax.swing.JLabel n7;
    private javax.swing.JLabel p1;
    private javax.swing.JLabel p2;
    private javax.swing.JLabel p3;
    private javax.swing.JLabel p4;
    private javax.swing.JLabel p5;
    private javax.swing.JLabel p6;
    private javax.swing.JLabel p7;
    private javax.swing.JLabel s1;
    private javax.swing.JLabel s2;
    private javax.swing.JLabel s3;
    private javax.swing.JLabel s4;
    private javax.swing.JLabel s5;
    private javax.swing.JLabel s6;
    private javax.swing.JLabel s7;
    // End of variables declaration//GEN-END:variables
}
