/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package User_end.Booking_Event;

import User_end.Event_pool.Venue_3;
import User_end.Event_pool.Venue_1;
import User_end.Event_pool.Venue_4;
import User_end.Event_pool.Venue_2;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author Atharva Sahani
 */
public class Booking_event_venue_home extends javax.swing.JFrame {

    /**
     * Creates new form Booking_event_venue_home
     */
    public Booking_event_venue_home() {
        initComponents();
        try{
           Connection con=null;
           Class.forName("oracle.jdbc.driver.OracleDriver");
           con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521/xe","system","vedaang" );
           PreparedStatement pst=con.prepareStatement("Select * from list_of_venues" );
           ResultSet x=pst.executeQuery();
           String sno[]=new String[7];
           String name[]=new String[7];
           int i=0;
           while(x.next())
           {
           sno[i]=x.getString(1);
           name[i]=x.getString(2);
           i++;
           }
           s1.setText(sno[0]);
           s2.setText(sno[1]);
           s3.setText(sno[2]);
           s4.setText(sno[3]);
           n1.setText(name[0]);
           n2.setText(name[1]);
           n3.setText(name[2]);
           n4.setText(name[3]);
           con.close();
        }catch(Exception e)
        {
            System.out.println(e);
            System.out.println("e");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        n1 = new javax.swing.JLabel();
        n2 = new javax.swing.JLabel();
        n4 = new javax.swing.JLabel();
        n3 = new javax.swing.JLabel();
        s1 = new javax.swing.JLabel();
        s4 = new javax.swing.JLabel();
        s3 = new javax.swing.JLabel();
        s2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setText("VENUES");

        jLabel2.setText("jLabel2");
        jLabel2.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel2MouseMoved(evt);
            }
        });
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setText("jLabel3");
        jLabel3.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setText("jLabel2");
        jLabel4.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel5.setText("jLabel3");
        jLabel5.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        n1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        n1.setForeground(new java.awt.Color(102, 0, 102));
        n1.setText("POOLWAY SIDE");

        n2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        n2.setForeground(new java.awt.Color(0, 0, 153));
        n2.setText("GARDEN SIDE VIEW");

        n4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        n4.setForeground(new java.awt.Color(102, 0, 0));
        n4.setText("CONFERENCE ROOM");

        n3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        n3.setForeground(new java.awt.Color(255, 255, 255));
        n3.setText("BANQUET HALL VIEW");

        s1.setText("sss");

        s4.setText("sss");

        s3.setText("sss");

        s2.setText("sss");

        jButton1.setText("Press To Book");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Press To Book");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Press To Book");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Press To Book");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(s1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(s3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(s2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(s4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(n3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                    .addComponent(n4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(80, 80, 80)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(n2, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                    .addComponent(n1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(80, 80, 80)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(s1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(n1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(n2)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(n3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(n4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(72, 72, 72))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        new Booking_event_home().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        new Booking_event_home().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        new Booking_event_home(). setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseMoved

  /*class A1 extends Thread{
       Event_pool.Venue_1 myFrame1;
       public void run (){
    try {
                Thread.sleep(2000);
            } catch (InterruptedException e) {
                System.out.println(e);}
      myFrame1 = new Venue_1();
      System.out.println("start thread screen 1");
      try {
                Thread.sleep(2000);
            } catch (InterruptedException e) {
                System.out.println(e);}
          System.out.println(" thread screen 1  ended");
        try{
          myFrame1.disposefunction();
        }catch(Exception e)
        {
            System.out.println(e);
        }
        }
        
  }   
class A2 extends Thread{
        Event_pool.Venue_2 myFrame2;
      public void run(){
    try {
                Thread.sleep(2000);
            } catch (InterruptedException e) {
                System.out.println(e);}
      myFrame2 = new Venue_2();
       System.out.println("start thread screen 2");   
        try {
                Thread.sleep(2000);
            } catch (InterruptedException e) {
                System.out.println(e);}
          System.out.println(" thread screen 2  ended");
         myFrame2.disposefunction();
   }
  }   
class A3 extends Thread{
        Event_pool.Venue_3 myFrame3;
       public void run(){
    try {
                Thread.sleep(2000);
            } catch (InterruptedException e) {
                System.out.println(e);}
      myFrame3 = new Venue_3();
      System.out.println("start thread screen 3");
       try {
                Thread.sleep(2000);
            } catch (InterruptedException e) {
                System.out.println(e);}
          System.out.println(" thread screen 3  ended");
         myFrame3.disposefunction();
   }
  }   
class A4 extends Thread{
        Event_pool.Venue_4 myFrame4;
      public void run(){ 
    try {
                Thread.sleep(2000);
            } catch (InterruptedException e) {
                System.out.println(e);}
      myFrame4 = new Venue_4();
      System.out.println("start thread screen 4");
       try {
                Thread.sleep(2000);
            } catch (InterruptedException e) {
                System.out.println(e);}
          System.out.println(" thread screen 4  ended");
        myFrame4.disposefunction();
   }
}
A1 b1=new A1();
            A2 b2=new A2();
            A3 b3=new A3();
            A4 b4=new A4();
            b1.start();
            
             try {
                Thread.sleep(2000);
            } catch (InterruptedException e) {
                System.out.println(e);}
            b2.start();
             try {
                Thread.sleep(2000);
            } catch (InterruptedException e) {
                System.out.println(e);}
            b3.start();
             try {
                Thread.sleep(2000);
            } catch (InterruptedException e) {
                System.out.println(e);}
            b4.start();
             try {
                Thread.sleep(2000);
            } catch (InterruptedException e) {
                System.out.println(e);}
  
    */
 
    }//GEN-LAST:event_jLabel2MouseMoved

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        new Booking_event_home().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try{
           Connection con=null,con1=null;
           Class.forName("oracle.jdbc.driver.OracleDriver");
           con1=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521/xe","system","vedaang" );
           con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521/xe","system","vedaang" );
           PreparedStatement pst=con.prepareStatement("Insert into billing_venue_temporary(S.no,venue_name,Price_per_hour ,values(?,?,?)");
           PreparedStatement pst1=con1.prepareStatement("Select * from venue_list");
           String sno,name,price;
           ResultSet x=pst1.executeQuery();
           int check=1;
           while(x.next())
           {
           sno=x.getString(1);
           name=x.getString(2);
           price=x.getString(3);
           if(check==Integer.parseInt(sno))
           {
           pst.setString(1,sno);
           pst.setString(2,name);
           pst.setString(3,price);
           pst.executeUpdate();
           break;
           }
           }
           
           con.close();
           con1.close();
            }catch(Exception e)
        {
            System.out.println(e);
            System.out.println("e1");
            
        }
        new User_end.Booking_Event.Billing_event_venue().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         try{
           Connection con=null,con1=null;
           Class.forName("oracle.jdbc.driver.OracleDriver");
           con1=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521/xe","system","vedaang" );
           con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521/xe","system","vedaang" );
           PreparedStatement pst=con.prepareStatement("Insert into billing_venue_temporary(S.no,venue_name,Price_per_hour ,values(?,?,?)");
           PreparedStatement pst1=con1.prepareStatement("Select * from venue_list");
           String sno,name,price;
           int check=2;
           ResultSet x=pst1.executeQuery();
          while(x.next())
           {
           sno=x.getString(1);
           name=x.getString(2);
           price=x.getString(3);
           if(check==Integer.parseInt(sno))
           {
           pst.setString(1,sno);
           pst.setString(2,name);
           pst.setString(3,price);
           pst.executeUpdate();
           break;
           }
           }
           con.close();
           con1.close();
            }catch(Exception e)
        {
            System.out.println(e);
            System.out.println("e2");
        }
        new User_end.Booking_Event.Billing_event_venue().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
           Connection con=null,con1=null;
           Class.forName("oracle.jdbc.driver.OracleDriver");
           con1=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521/xe","system","vedaang" );
           con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521/xe","system","vedaang" );
           PreparedStatement pst=con.prepareStatement("Insert into billing_venue_temporary(S_NO,VENUE_NAME,PRICE_PER_HOUR) values(?,?,?)");
           PreparedStatement pst1=con1.prepareStatement("Select * from venue_list");
           String sno,name,price;
           int check=3;
           ResultSet x=pst1.executeQuery();
          while(x.next())
           {
           sno=x.getString(1);
           System.out.println(sno);
           name=x.getString(2);
           System.out.println(name);
           price=x.getString(3);
           System.out.println(price);
           if(check==Integer.parseInt(sno))
           {
           pst.setString(1,sno);
           System.out.println(sno);
           pst.setString(2,name);
           System.out.println(name);
           pst.setString(3,price);
           System.out.println(price);
           pst.executeUpdate();
           break;
           }
           }
           con.close();
           con1.close();
            }catch(Exception e)
        {
            System.out.println(e);
            System.out.println("e3");
        }
        new User_end.Booking_Event.Billing_event_venue().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try{
           Connection con=null,con1=null;
           Class.forName("oracle.jdbc.driver.OracleDriver");
           con1=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521/xe","system","vedaang" );
           con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521/xe","system","vedaang" );
           PreparedStatement pst=con.prepareStatement("Insert into billing_venue_temporary(S.no,venue_name,Price_per_hour ,values(?,?,?)");
           PreparedStatement pst1=con1.prepareStatement("Select * from venue_list");
           String sno,name,price;
           int check=4;
           ResultSet x=pst1.executeQuery();
           while(x.next())
           {
           sno=x.getString(1);
           name=x.getString(2);
           price=x.getString(3);
           if(check==Integer.parseInt(sno))
           {
           pst.setString(1,sno);
           pst.setString(2,name);
           pst.setString(3,price);
           int y=pst.executeUpdate();
            System.out.println(y);
           break;
           }
           }
          
           con.close();
           con1.close();
            }catch(Exception e)
        {
            System.out.println(e);
            System.out.println("e4");
        }
        new User_end.Booking_Event.Billing_event_venue().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Booking_event_venue_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Booking_event_venue_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Booking_event_venue_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Booking_event_venue_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Booking_event_venue_home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel n1;
    private javax.swing.JLabel n2;
    private javax.swing.JLabel n3;
    private javax.swing.JLabel n4;
    private javax.swing.JLabel s1;
    private javax.swing.JLabel s2;
    private javax.swing.JLabel s3;
    private javax.swing.JLabel s4;
    // End of variables declaration//GEN-END:variables
}
