/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Starting_pages.Signup_pages;
import java.util.concurrent.ThreadLocalRandom;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.io.*;
import java.nio.charset.Charset;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Atharva Sahani
 */
public class Signup_user_id_details extends javax.swing.JFrame {
  class details{
        String name1=null;
        String emailid1=null;
        String contactno1=null;
        String address1=null;
        String state1=null;
        String country1=null;
        String pincode1=null;
        String alternateemailid1=null;
        String gender1=null;
           } 
             details d1=new details();
    /**
     * Creates new form Signup_user_id_details
     */
    public Signup_user_id_details() {
        initComponents();
        details d1=new details();
        String line=null;
        try {
          InputStream fis = new FileInputStream("D:\\files\\signup_personal_details.txt");
          InputStreamReader isr = new InputStreamReader(fis, Charset.forName("UTF-8"));
          BufferedReader br = new BufferedReader(isr); 
          
                while((line=br.readLine())!=null)
                  {
                           String[] words;
                           words=line.split(":");
                           if(words[0].equals("name"))
                           d1.name1=words[1];
                           if(words[0].equals("Email id"))
                           d1.emailid1=words[1];
                           if(words[0].equals("Contact number"))
                           d1.contactno1=words[1];
                           if(words[0].equals("Address"))
                           d1.address1=words[1];
                           if(words[0].equals("State"))
                           d1.state1=words[1];
                           if(words[0].equals("Country"))
                           d1.country1=words[1];
                           if(words[0].equals("Pincode"))
                           d1.pincode1=words[1];
                           if(words[0].equals("Alternate Email Id"))
                           d1.alternateemailid1=words[1];
                           if(words[0].equals("Gender"))
                           d1.gender1=words[1];
                           
                           System.out.println("hello");
                           
                  }
           
          }catch(Exception e)
          {
              System.out.println(e);
              System.out.println(d1.name1);
              
          }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        t2 = new javax.swing.JPasswordField();
        t3 = new javax.swing.JPasswordField();
        t1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        t4 = new javax.swing.JTextArea();
        t5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 1000));
        getContentPane().setLayout(null);

        jLabel6.setText("Enter Here:-");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 387, 94, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Enter User Id Details.....................................");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 11, 834, 50);

        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Username:-");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 77, 94, 30);

        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Password:-");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 148, 94, 30);

        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Confirm Password:-");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 223, 94, 30);

        jButton1.setText("Signup");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(196, 445, 297, 40);

        jLabel4.setText("Captcha:-");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 311, 94, 30);
        getContentPane().add(t2);
        t2.setBounds(127, 148, 403, 30);
        getContentPane().add(t3);
        t3.setBounds(127, 223, 403, 30);
        getContentPane().add(t1);
        t1.setBounds(127, 77, 403, 30);

        t4.setColumns(20);
        t4.setRows(5);
        jScrollPane2.setViewportView(t4);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(122, 285, 408, 96);
        getContentPane().add(t5);
        t5.setBounds(122, 391, 313, 32);

        jLabel7.setIcon(new javax.swing.ImageIcon("D:\\553717.jpg")); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 840, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String username=t1.getText();
       String password=t2.getText();
       String confirmpassword=t3.getText();
       String capthcainput=t5.getText();
       String username1=null;
       String password1=null;
         String name1=null;
        String emailid1=null;
        String contactno1=null;
        String address1=null;
        String state1=null;
        String country1=null;
        String pincode1=null;
        String alternateemailid1=null;
        String gender1=null;
        System.out.println("hello111");
        try
       {
           Connection con=null,con1=null;
           Class.forName("oracle.jdbc.driver.OracleDriver");
           con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521/xe","system","vedaang" );
           con1=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521/xe","system","vedaang" );
           PreparedStatement pst=con.prepareStatement("update login set username=? and password=? ");
           PreparedStatement pst1=con1.prepareStatement("Select * from login");
           ResultSet x=pst1.executeQuery();
           ResultSet y=pst1.executeQuery();
           System.out.println("hello12323");
           while(x.next())
           {    
                name1=x.getString(1);
              emailid1=x.getString(2);
              contactno1=x.getString(3);
              address1=x.getString(4);
              state1=x.getString(5);
              country1=x.getString(6);
              pincode1=x.getString(7);
              alternateemailid1=x.getString(8);
              gender1=x.getString(9);
            System.out.println("hello1212111221121");
               username1=x.getString(10);
               password1=x.getString(11);
               System.out.println("hello");
        /*   if(username1.equals(username) && password1.equals(password))
           {
               System.out.println("hello111111111111111111111111111111111111111111"); 
               JOptionPane.showMessageDialog(this,"DATA SIMILAR IN DATABASE.CHANGE SOME ENTRIES.USER EXSITS");
           }
               */
           }
               
           System.out.println("hello1");
           while(y.next())
               {
                System.out.println("vedaang");
               name1=y.getString(1);
              emailid1=y.getString(2);
              contactno1=y.getString(3);
              address1=y.getString(4);
              state1=y.getString(5);
              country1=y.getString(6);
              pincode1=y.getString(7);
              alternateemailid1=y.getString(8);
              gender1=y.getString(9);
            System.out.println("12121");
                   if(name1==d1.name1 && emailid1==d1.emailid1 && contactno1==d1.contactno1 && address1==d1.address1 && state1==d1.state1 && country1==d1.country1 && pincode1==d1.pincode1 && alternateemailid1==d1.alternateemailid1 && gender1==d1.gender1 )         
              {
                  if(confirmpassword.equals(password))
           {
           pst.setString(1,username);
           pst.setString(2,password);
           int executeUpdate = pst.executeUpdate();
           
           }
                  
           else
           {
                JOptionPane.showMessageDialog(this,"Please verify :Passwords don't match");
           }
                   }
                   }
     
            
           con.close();
           con1.close();
       }catch(Exception e)
       { 
           System.out.println(e);
       }
                
         
    }//GEN-LAST:event_jButton1ActionPerformed
/*int x[]= new int[10];
        for(int i=0;i<10;i++)
        { 
            x[i]= ThreadLocalRandom.current().nextInt(0, 20 + 1);
            t4.setText(String.valueOf(x[i]));
        }*/
    /*
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup_user_id_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup_user_id_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup_user_id_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup_user_id_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup_user_id_details().setVisible(true);
            
                 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField t1;
    private javax.swing.JPasswordField t2;
    private javax.swing.JPasswordField t3;
    private javax.swing.JTextArea t4;
    private javax.swing.JTextField t5;
    // End of variables declaration//GEN-END:variables
}
