/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Starting_pages.Signup_pages;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.OutputStreamWriter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Atharva Sahani
 */
public class Signup_personal_details extends javax.swing.JFrame {
        class details{
        String name1;
        String emailid1;
        String contactno1;
        String address1;
        String state1;
        String country1;
        String pincode1;
        String alternateemailid1;
        String gender1;

        details() {
            this.gender1 = null;
            this.alternateemailid1 = null;
            this.pincode1 = null;
            this.address1 = null;
            this.contactno1 = null;
            this.emailid1 = null;
            this.country1 = null;
            this.state1 = null;
            this.name1 = null;
        }
           }    
    /**
     * Creates new form Signup_personal_details_1
     */
    public Signup_personal_details() {
        initComponents();
       setSize(1650,1080);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        t4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        t5 = new javax.swing.JTextField();
        t6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        t7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        t8 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        t9 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        getContentPane().setLayout(null);

        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Name:-");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(21, 70, 117, 33);
        getContentPane().add(t1);
        t1.setBounds(480, 70, 345, 33);

        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Email Id:-");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(21, 114, 117, 33);
        getContentPane().add(t2);
        t2.setBounds(480, 110, 345, 33);

        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Contact no:-");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(21, 158, 117, 33);
        getContentPane().add(t3);
        t3.setBounds(480, 160, 345, 33);

        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Address:-");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(21, 202, 117, 33);
        getContentPane().add(t4);
        t4.setBounds(480, 210, 345, 33);

        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("State:-");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(21, 246, 117, 33);
        getContentPane().add(t5);
        t5.setBounds(480, 250, 345, 33);
        getContentPane().add(t6);
        t6.setBounds(480, 290, 345, 33);

        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("Country:-");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(21, 290, 117, 33);

        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("Pincode:-");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(21, 334, 117, 33);
        getContentPane().add(t7);
        t7.setBounds(480, 330, 345, 33);

        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("Alternate Email Id:-");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(21, 378, 117, 33);
        getContentPane().add(t8);
        t8.setBounds(480, 370, 345, 33);

        jLabel10.setForeground(new java.awt.Color(240, 240, 240));
        jLabel10.setText("Gender:-");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(21, 422, 117, 33);

        t9.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female", "Other" }));
        getContentPane().add(t9);
        t9.setBounds(600, 420, 162, 33);

        jButton1.setText("Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(230, 490, 282, 34);

        jLabel12.setForeground(new java.awt.Color(240, 240, 240));
        getContentPane().add(jLabel12);
        jLabel12.setBounds(0, 0, 1550, 830);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        details d1=new details();
        d1.name1=t1.getText();
        d1.emailid1=t2.getText();
        d1.contactno1=t3.getText();
        d1.address1=t4.getText();
        d1.state1 =t5.getText();
        d1.country1=t6.getText();
        d1.pincode1=t7.getText();
        d1.alternateemailid1=t8.getText();
        d1.gender1=(String)t9.getSelectedItem();
        try
       {String name1=null;
        String emailid1=null;
        String contactno1=null;
        String address1=null;
        String state1=null;
        String country1=null;
        String pincode1=null;
        String alternateemailid1=null;
        String gender1=null;
        
           Connection con=null,con1=null;
           Class.forName("oracle.jdbc.driver.OracleDriver");
           con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521/xe","system","vedaang" );
           con1=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521/xe","system","vedaang" );
            System.out.println("record byee......");
           PreparedStatement pst=con.prepareStatement("insert into login(name,email_id,contact_no,address,state,country,pincode,alternate_email_id,gender) values(?,?,?,?,?,?,?,?,?)");
           PreparedStatement pst1=con1.prepareStatement("Select * from login");
           ResultSet x=pst1.executeQuery();
           pst.setString(1,d1.name1);
           pst.setString(2,d1.emailid1);
           pst.setString(3,d1.contactno1);
           pst.setString(4,d1.address1);
           pst.setString(5,d1.state1);
           pst.setString(6,d1.country1);
           pst.setString(7,d1.pincode1);
           pst.setString(8,d1.alternateemailid1);
           pst.setString(9,d1.gender1);
            System.out.println("record hi");
           while(x.next())
           {
            name1=x.getString(1);
              emailid1=x.getString(2);
              contactno1=x.getString(3);
              address1=x.getString(4);
              state1=x.getString(5);
              country1=x.getString(6);
              pincode1=x.getString(7);
              alternateemailid1=x.getString(8);
              gender1=x.getString(9);
              System.out.println(name1);
                     
              
            System.out.println("record hi2");
            if(name1==d1.name1 && emailid1==d1.emailid1 && contactno1==d1.contactno1 && address1==d1.address1 && state1==d1.state1 && country1==d1.country1 && pincode1==d1.pincode1 && alternateemailid1==d1.alternateemailid1 && gender1==d1.gender1 ) 
           {
               JOptionPane.showMessageDialog(this,"DATA SIMILAR IN DATABASE.CHANGE SOME ENTRIES.USER EXSITS");
           
           }
           }
           System.out.println("record hi1");
           int y=pst.executeUpdate();
           if(y>0)
           {
               System.out.println("record inserted");
           }
        File fout = new File("D:\\files\\signup_personal_details.txt");
	FileOutputStream fos = new FileOutputStream(fout);
 
	BufferedWriter bw = new BufferedWriter(new OutputStreamWriter(fos));
        String s="User details";
        bw.write(s);
        bw.newLine();
        bw.append("Name:");
        bw.append(d1.name1);
	bw.newLine();
        bw.append("Email id:");
        bw.append(d1.emailid1);
	bw.newLine();
        bw.append("Contact number:");
        bw.append(d1.contactno1);
	bw.newLine();
        bw.append("Address:");
        bw.append(d1.address1);
	bw.newLine();
        bw.append("State:");
        bw.append(d1.state1);
	bw.newLine();
        bw.append("Country:");
        bw.append(d1.country1);
	bw.newLine();
        bw.append("Pincode:");
        bw.append(d1.pincode1);
	bw.newLine();
        bw.append("Alternate Email Id:");
        bw.append(d1.alternateemailid1);
	bw.newLine();
        bw.append("Gender:");
        bw.append(d1.gender1);
	bw.newLine();
	bw.close();
        con.close();
        con1.close();
           
       }catch(Exception e)
       {
           System.out.println(e);
           
       }
          
         new Signup_user_id_details().setVisible(true);
         this.dispose();
                                            
           
   
             
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup_personal_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup_personal_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup_personal_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup_personal_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 
                new Signup_personal_details().setVisible(true);
                                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    private javax.swing.JTextField t8;
    private javax.swing.JComboBox t9;
    // End of variables declaration//GEN-END:variables
}
